apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tmp
  name: tmp
  namespace: vault
spec:
  containers:
  - image: alpine:3.7
    imagePullPolicy: IfNotPresent
    name: tmp
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: vault-auth
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: vault-auth
  serviceAccountName: vault-auth
  terminationGracePeriodSeconds: 30
  volumes:
  - name: vault-auth
    secret:
      defaultMode: 420
      secretName: vault-auth-token